// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2017-12-15 14:43:05.6283198 +0800 CST m=+0.040113900

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "后台管理模块",
        "title": "GOLANG-GIN",
        "contact": {
            "email": "mrjnamei@gmail.com"
        },
        "license": {},
        "version": "1.0"
    },
    "basePath": "/v1",
    "paths": {
        "/file/upload": {
            "post": {
                "description": "asdasdasdasd",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "common"
                ],
                "summary": "asd",
                "operationId": "file.upload",
                "parameters": [
                    {
                        "type": "file",
                        "description": "sss",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "We need ID!!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.File"
                        }
                    },
                    "404": {
                        "description": "Can not find ID",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.APIError": {
            "type": "object",
            "properties": {
                "CreatedAt": {
                    "type": "string"
                },
                "ErrorCode": {
                    "type": "int"
                },
                "ErrorMessage": {
                    "type": "string"
                }
            }
        },
        "model.File": {
            "type": "object",
            "properties": {
                "Filename": {
                    "type": "string"
                },
                "Id": {
                    "type": "string"
                },
                "Md5": {
                    "type": "string"
                },
                "Url": {
                    "type": "string"
                },
                "UserId": {
                    "type": "int64"
                }
            }
        }
    },
    "tags": [
        {
            "description": "asdasdasd",
            "name": "users"
        },
        {
            "description": "asdasdasdasd",
            "name": "contents"
        }
    ]
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
